# Generated by Django 5.0.6 on 2024-06-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_hw3', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to='products/'),
        ),
    ]
